# Generated by Django 4.2.23 on 2026-02-09 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_publiccoursecomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PublicCourseComment',
        ),
    ]
