# Generated by Django 4.2.23 on 2026-02-09 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_remove_public_course_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='userRole',
            new_name='user_role',
        ),
        migrations.AlterUniqueTogether(
            name='usercourse',
            unique_together={('user', 'course')},
        ),
    ]
